package application;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyCode;
import javafx.stage.Stage;

public class LoginController {
	@FXML
	private PasswordField tfPassword;
	@FXML
	private TextField tfIdNum;
	@FXML
	private Button btLoginBR;
	@FXML
	private Button btLoginYS;
	@FXML
	private Button btRegisterBR;
	@FXML
	private Button btExit;
	@FXML
	private Button btRegisterYS;
	private Stage stage;

	public void init() {
		stage.getScene().setOnKeyPressed(e -> {
			if (e.getCode() == KeyCode.ENTER) {
				if (btLoginBR.isFocused()) {
					this.loginBRClicked(new ActionEvent());
				} else if (btLoginYS.isFocused()) {
					this.loginYSClicked(new ActionEvent());
				} else if (btRegisterBR.isFocused()) {
					this.registerBRClicked(new ActionEvent());
				} else if (btRegisterYS.isFocused()) {
					this.registerYSClicked(new ActionEvent());
				} else if (btExit.isFocused()) {
					this.exitClicked(new ActionEvent());
				}
			}
		});
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	private boolean isLoginBROK(String idNum, String password) {
		try (Connection connection = ConnectionDB.getConnection()) {
			String sql_ifMatch = "select * from T_BRXX where BRBH = ? and DLKL = ?";
			PreparedStatement statement = connection.prepareStatement(sql_ifMatch);
			statement.setString(1, idNum);
			statement.setString(2, password);
			ResultSet resultSet = statement.executeQuery();
			return resultSet.next();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return false;
	}

	private boolean isLoginYSOK(String idNum, String password) {
		try (Connection connection = ConnectionDB.getConnection()) {
			String sql_ifMatch = "select * from T_KSYS where YSBH = ? and DLKL = ?";
			PreparedStatement statement = connection.prepareStatement(sql_ifMatch);
			statement.setString(1, idNum);
			statement.setString(2, password);
			ResultSet resultSet = statement.executeQuery();
			return resultSet.next();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return false;
	}

	// Event Listener on Button[#btLoginBR].onAction
	@FXML
	public void loginBRClicked(ActionEvent event) {
		// TODO Autogenerated
		// Read file fxml and draw interface.
		try {
			String idNum = tfIdNum.getText().trim();
			String password = tfPassword.getText().trim();
			if (isLoginBROK(idNum, password)) {
				ConnectionDB.updateBRLoginTime(idNum);
				FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("guahao.fxml"));
				Parent root = fxmlLoader.load();
				GuahaoController controller = fxmlLoader.getController();
				controller.setIdNum(idNum);
				Stage st = new Stage();
				controller.setStage(st);
				st.setTitle("My Application");
				st.setScene(new Scene(root));
				controller.init();
				stage.close();
				st.show();
			} else {
				JOptionPane.showMessageDialog(null, "请检查编号与密码");
			}
		} catch (IOException e) {
			// TODO: handle exception
		}
	}

	// Event Listener on Button[#btRegisterBR].onAction
	@FXML
	public void registerBRClicked(ActionEvent event) {
		// TODO Autogenerated
		try {
			// Read file fxml and draw interface.
			FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("registerBR.fxml"));
			Parent root = fxmlLoader.load();
			registerBRController controller = fxmlLoader.getController();
			Stage st = new Stage();
			st.setResizable(false);
			controller.setStage(st);
			st.setTitle("My Application");
			st.setScene(new Scene(root));
			controller.init();
			st.show();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btLoginYS].onAction
	@FXML
	public void loginYSClicked(ActionEvent event) {
		// TODO Autogenerated
		try {
			String idNum = tfIdNum.getText().trim();
			String password = tfPassword.getText().trim();
			if (isLoginYSOK(idNum, password)) {
				ConnectionDB.updateYSLoginTime(idNum);
				System.out.println("Login");
			} else {
				JOptionPane.showMessageDialog(null, "请检查编号与密码");
			}
		} finally {

		}
	}

	// Event Listener on Button[#btRegisterYS].onAction
	@FXML
	public void registerYSClicked(ActionEvent event) {
		// TODO Autogenerated
		try {
			// Read file fxml and draw interface.
			FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("registerYS.fxml"));
			Parent root = fxmlLoader.load();
			registerYSController controller = fxmlLoader.getController();
			Stage st = new Stage();
			st.setResizable(false);
			controller.setStage(st);
			st.setTitle("My Application");
			st.setScene(new Scene(root));
			controller.init();
			st.show();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btExit].onAction
	@FXML
	public void exitClicked(ActionEvent event) {
		stage.close();
		// TODO Autogenerated
	}

}
